
export class Icon {
    class: string;
    name: string;
}
export const IconsArray: Icon[] = [

    { class: "fa fa-500px", name: "500px" },
    { class: "fa fa-adjust", name: "Adjust" },
    { class: "fa fa-adn", name: "Adn" },
    { class: "fa fa-align-center", name: "Align Center" },
    { class: "fa fa-align-justify", name: "Align Justify" },
    { class: "fa fa-align-left", name: "Align Left" },
    { class: "fa fa-align-right", name: "Align Right" },
    { class: "fa fa-amazon", name: "Amazon" },
    { class: "fa fa-ambulance", name: "Ambulance" },
    { class: "fa fa-anchor", name: "Anchor" },
    { class: "fa fa-android", name: "Android" },
    { class: "fa fa-angellist", name: "Angellist" },
    { class: "fa fa-angle-double-down", name: "Angle Double Down" },
    { class: "fa fa-angle-double-left", name: "Angle Double Left" },
    { class: "fa fa-angle-double-right", name: "Angle Double Right" },
    { class: "fa fa-angle-double-up", name: "Angle Double Up" },
    { class: "fa fa-angle-down", name: "Angle Down" },
    { class: "fa fa-angle-left", name: "Angle Left" },
    { class: "fa fa-angle-right", name: "Angle Right" },
    { class: "fa fa-angle-up", name: "Angle Up" },
    { class: "fa fa-apple", name: "Apple" },
    { class: "fa fa-archive", name: "Archive" },
    { class: "fa fa-area-chart", name: "Area Chart" },
    { class: "fa fa-arrow-circle-down", name: "Arrow Circle Down" },
    { class: "fa fa-arrow-circle-left", name: "Arrow Circle Left" },
    { class: "fa fa-arrow-circle-o-down", name: "Arrow Circle O Down" },
    { class: "fa fa-arrow-circle-o-left", name: "Arrow Circle O Left" },
    { class: "fa fa-arrow-circle-o-right", name: "Arrow Circle O Right" },
    { class: "fa fa-arrow-circle-o-up", name: "Arrow Circle O Up" },
    { class: "fa fa-arrow-circle-right", name: "Arrow Circle Right" },
    { class: "fa fa-arrow-circle-up", name: "Arrow Circle Up" },
    { class: "fa fa-arrow-down", name: "Arrow Down" },
    { class: "fa fa-arrow-left", name: "Arrow Left" },
    { class: "fa fa-arrow-right", name: "Arrow Right" },
    { class: "fa fa-arrow-up", name: "Arrow Up" },
    { class: "fa fa-arrows", name: "Arrows" },
    { class: "fa fa-arrows-alt", name: "Arrows Alt" },
    { class: "fa fa-arrows-h", name: "Arrows H" },
    { class: "fa fa-arrows-v", name: "Arrows V" },
    { class: "fa fa-asterisk", name: "Asterisk" },
    { class: "fa fa-at", name: "At" },
    { class: "fa fa-automobile", name: "Automobile" },
    { class: "fa fa-backward", name: "Backward" },
    { class: "fa fa-balance-scale", name: "Balance Scale" },
    { class: "fa fa-ban", name: "Ban" },
    { class: "fa fa-bank", name: "Bank" },
    { class: "fa fa-bar-chart", name: "Bar Chart" },
    { class: "fa fa-bar-chart-o", name: "Bar Chart O" },
    { class: "fa fa-barcode", name: "Barcode" },
    { class: "fa fa-bars", name: "Bars" },
    { class: "fa fa-battery-0", name: "Battery 0" },
    { class: "fa fa-battery-1", name: "Battery 1" },
    { class: "fa fa-battery-2", name: "Battery 2" },
    { class: "fa fa-battery-3", name: "Battery 3" },
    { class: "fa fa-battery-4", name: "Battery 4" },
    { class: "fa fa-battery-empty", name: "Battery Empty" },
    { class: "fa fa-battery-full", name: "Battery Full" },
    { class: "fa fa-battery-half", name: "Battery Half" },
    { class: "fa fa-battery-quarter", name: "Battery Quarter" },
    { class: "fa fa-battery-three-quarters", name: "Battery Three Quarters" },
    { class: "fa fa-bed", name: "Bed" },
    { class: "fa fa-beer", name: "Beer" },
    { class: "fa fa-behance", name: "Behance" },
    { class: "fa fa-behance-square", name: "Behance Square" },
    { class: "fa fa-bell", name: "Bell" },
    { class: "fa fa-bell-o", name: "Bell O" },
    { class: "fa fa-bell-slash", name: "Bell Slash" },
    { class: "fa fa-bell-slash-o", name: "Bell Slash O" },
    { class: "fa fa-bicycle", name: "Bicycle" },
    { class: "fa fa-binoculars", name: "Binoculars" },
    { class: "fa fa-birthday-cake", name: "Birthday Cake" },
    { class: "fa fa-bitbucket", name: "Bitbucket" },
    { class: "fa fa-bitbucket-square", name: "Bitbucket Square" },
    { class: "fa fa-bitcoin", name: "Bitcoin" },
    { class: "fa fa-black-tie", name: "Black Tie" },
    { class: "fa fa-bluetooth", name: "Bluetooth" },
    { class: "fa fa-bluetooth-b", name: "Bluetooth B" },
    { class: "fa fa-bold", name: "Bold" },
    { class: "fa fa-bolt", name: "Bolt" },
    { class: "fa fa-bomb", name: "Bomb" },
    { class: "fa fa-book", name: "Book" },
    { class: "fa fa-bookmark", name: "Bookmark" },
    { class: "fa fa-bookmark-o", name: "Bookmark O" },
    { class: "fa fa-briefcase", name: "Briefcase" },
    { class: "fa fa-btc", name: "Btc" },
    { class: "fa fa-bug", name: "Bug" },
    { class: "fa fa-building", name: "Building" },
    { class: "fa fa-building-o", name: "Building O" },
    { class: "fa fa-bullhorn", name: "Bullhorn" },
    { class: "fa fa-bullseye", name: "Bullseye" },
    { class: "fa fa-bus", name: "Bus" },
    { class: "fa fa-buysellads", name: "Buysellads" },
    { class: "fa fa-cab", name: "Cab" },
    { class: "fa fa-calculator", name: "Calculator" },
    { class: "fa fa-calendar", name: "Calendar" },
    { class: "fa fa-calendar-check-o", name: "Calendar Check O" },
    { class: "fa fa-calendar-minus-o", name: "Calendar Minus O" },
    { class: "fa fa-calendar-o", name: "Calendar O" },
    { class: "fa fa-calendar-plus-o", name: "Calendar Plus O" },
    { class: "fa fa-calendar-times-o", name: "Calendar Times O" },
    { class: "fa fa-camera", name: "Camera" },
    { class: "fa fa-camera-retro", name: "Camera Retro" },
    { class: "fa fa-car", name: "Car" },
    { class: "fa fa-caret-down", name: "Caret Down" },
    { class: "fa fa-caret-left", name: "Caret Left" },
    { class: "fa fa-caret-right", name: "Caret Right" },
    { class: "fa fa-caret-square-o-down", name: "Caret Square O Down" },
    { class: "fa fa-caret-square-o-left", name: "Caret Square O Left" },
    { class: "fa fa-caret-square-o-right", name: "Caret Square O Right" },
    { class: "fa fa-caret-square-o-up", name: "Caret Square O Up" },
    { class: "fa fa-caret-up", name: "Caret Up" },
    { class: "fa fa-cart-arrow-down", name: "Cart Arrow Down" },
    { class: "fa fa-cart-plus", name: "Cart Plus" },
    { class: "fa fa-cc", name: "Cc" },
    { class: "fa fa-cc-amex", name: "Cc Amex" },
    { class: "fa fa-cc-diners-club", name: "Cc Diners Club" },
    { class: "fa fa-cc-discover", name: "Cc Discover" },
    { class: "fa fa-cc-jcb", name: "Cc Jcb" },
    { class: "fa fa-cc-mastercard", name: "Cc Mastercard" },
    { class: "fa fa-cc-paypal", name: "Cc Paypal" },
    { class: "fa fa-cc-stripe", name: "Cc Stripe" },
    { class: "fa fa-cc-visa", name: "Cc Visa" },
    { class: "fa fa-certificate", name: "Certificate" },
    { class: "fa fa-chain", name: "Chain" },
    { class: "fa fa-chain-broken", name: "Chain Broken" },
    { class: "fa fa-check", name: "Check" },
    { class: "fa fa-check-circle", name: "Check Circle" },
    { class: "fa fa-check-circle-o", name: "Check Circle O" },
    { class: "fa fa-check-square", name: "Check Square" },
    { class: "fa fa-check-square-o", name: "Check Square O" },
    { class: "fa fa-chevron-circle-down", name: "Chevron Circle Down" },
    { class: "fa fa-chevron-circle-left", name: "Chevron Circle Left" },
    { class: "fa fa-chevron-circle-right", name: "Chevron Circle Right" },
    { class: "fa fa-chevron-circle-up", name: "Chevron Circle Up" },
    { class: "fa fa-chevron-down", name: "Chevron Down" },
    { class: "fa fa-chevron-left", name: "Chevron Left" },
    { class: "fa fa-chevron-right", name: "Chevron Right" },
    { class: "fa fa-chevron-up", name: "Chevron Up" },
    { class: "fa fa-child", name: "Child" },
    { class: "fa fa-chrome", name: "Chrome" },
    { class: "fa fa-circle", name: "Circle" },
    { class: "fa fa-circle-o", name: "Circle O" },
    { class: "fa fa-circle-o-notch", name: "Circle O Notch" },
    { class: "fa fa-circle-thin", name: "Circle Thin" },
    { class: "fa fa-clipboard", name: "Clipboard" },
    { class: "fa fa-clock-o", name: "Clock O" },
    { class: "fa fa-clone", name: "Clone" },
    { class: "fa fa-close", name: "Close" },
    { class: "fa fa-cloud", name: "Cloud" },
    { class: "fa fa-cloud-download", name: "Cloud Download" },
    { class: "fa fa-cloud-upload", name: "Cloud Upload" },
    { class: "fa fa-cny", name: "Cny" },
    { class: "fa fa-code", name: "Code" },
    { class: "fa fa-code-fork", name: "Code Fork" },
    { class: "fa fa-codepen", name: "Codepen" },
    { class: "fa fa-codiepie", name: "Codiepie" },
    { class: "fa fa-coffee", name: "Coffee" },
    { class: "fa fa-cog", name: "Cog" },
    { class: "fa fa-cogs", name: "Cogs" },
    { class: "fa fa-columns", name: "Columns" },
    { class: "fa fa-comment", name: "Comment" },
    { class: "fa fa-comment-o", name: "Comment O" },
    { class: "fa fa-commenting", name: "Commenting" },
    { class: "fa fa-commenting-o", name: "Commenting O" },
    { class: "fa fa-comments", name: "Comments" },
    { class: "fa fa-comments-o", name: "Comments O" },
    { class: "fa fa-compass", name: "Compass" },
    { class: "fa fa-compress", name: "Compress" },
    { class: "fa fa-connectdevelop", name: "Connectdevelop" },
    { class: "fa fa-contao", name: "Contao" },
    { class: "fa fa-copy", name: "Copy" },
    { class: "fa fa-copyright", name: "Copyright" },
    { class: "fa fa-creative-commons", name: "Creative Commons" },
    { class: "fa fa-credit-card", name: "Credit Card" },
    { class: "fa fa-credit-card-alt", name: "Credit Card Alt" },
    { class: "fa fa-crop", name: "Crop" },
    { class: "fa fa-crosshairs", name: "Crosshairs" },
    { class: "fa fa-css3", name: "Css3" },
    { class: "fa fa-cube", name: "Cube" },
    { class: "fa fa-cubes", name: "Cubes" },
    { class: "fa fa-cut", name: "Cut" },
    { class: "fa fa-cutlery", name: "Cutlery" },
    { class: "fa fa-dashboard", name: "Dashboard" },
    { class: "fa fa-dashcube", name: "Dashcube" },
    { class: "fa fa-database", name: "Database" },
    { class: "fa fa-dedent", name: "Dedent" },
    { class: "fa fa-delicious", name: "Delicious" },
    { class: "fa fa-desktop", name: "Desktop" },
    { class: "fa fa-deviantart", name: "Deviantart" },
    { class: "fa fa-diamond", name: "Diamond" },
    { class: "fa fa-digg", name: "Digg" },
    { class: "fa fa-dollar", name: "Dollar" },
    { class: "fa fa-dot-circle-o", name: "Dot Circle O" },
    { class: "fa fa-download", name: "Download" },
    { class: "fa fa-dribbble", name: "Dribbble" },
    { class: "fa fa-dropbox", name: "Dropbox" },
    { class: "fa fa-drupal", name: "Drupal" },
    { class: "fa fa-edge", name: "Edge" },
    { class: "fa fa-edit", name: "Edit" },
    { class: "fa fa-eject", name: "Eject" },
    { class: "fa fa-ellipsis-h", name: "Ellipsis H" },
    { class: "fa fa-ellipsis-v", name: "Ellipsis V" },
    { class: "fa fa-empire", name: "Empire" },
    { class: "fa fa-envelope", name: "Envelope" },
    { class: "fa fa-envelope-o", name: "Envelope O" },
    { class: "fa fa-envelope-square", name: "Envelope Square" },
    { class: "fa fa-eraser", name: "Eraser" },
    { class: "fa fa-eur", name: "Eur" },
    { class: "fa fa-euro", name: "Euro" },
    { class: "fa fa-exchange", name: "Exchange" },
    { class: "fa fa-exclamation", name: "Exclamation" },
    { class: "fa fa-exclamation-circle", name: "Exclamation Circle" },
    { class: "fa fa-exclamation-triangle", name: "Exclamation Triangle" },
    { class: "fa fa-expand", name: "Expand" },
    { class: "fa fa-expeditedssl", name: "Expeditedssl" },
    { class: "fa fa-external-link", name: "External Link" },
    { class: "fa fa-external-link-square", name: "External Link Square" },
    { class: "fa fa-eye", name: "Eye" },
    { class: "fa fa-eye-slash", name: "Eye Slash" },
    { class: "fa fa-eyedropper", name: "Eyedropper" },
    { class: "fa fa-facebook", name: "fa facebook" },
    { class: "fa fa-facebook-f", name: "fa facebook F" },
    { class: "fa fa-facebook-official", name: "fa facebook Official" },
    { class: "fa fa-facebook-square", name: "fa facebook Square" },
    { class: "fa fa-fast-backward", name: "fa fast Backward" },
    { class: "fa fa-fast-forward", name: "fa fast Forward" },
    { class: "fa fa-fax", name: "fa fax" },
    { class: "fa fa-feed", name: "Feed" },
    { class: "fa fa-female", name: "Female" },
    { class: "fa fa-fighter-jet", name: "Fighter Jet" },
    { class: "fa fa-file", name: "File" },
    { class: "fa fa-file-archive-o", name: "File Archive O" },
    { class: "fa fa-file-audio-o", name: "File Audio O" },
    { class: "fa fa-file-code-o", name: "File Code O" },
    { class: "fa fa-file-excel-o", name: "File Excel O" },
    { class: "fa fa-file-image-o", name: "File Image O" },
    { class: "fa fa-file-movie-o", name: "File Movie O" },
    { class: "fa fa-file-o", name: "File O" },
    { class: "fa fa-file-pdf-o", name: "File Pdf O" },
    { class: "fa fa-file-photo-o", name: "File Photo O" },
    { class: "fa fa-file-picture-o", name: "File Picture O" },
    { class: "fa fa-file-powerpoint-o", name: "File Powerpoint O" },
    { class: "fa fa-file-sound-o", name: "File Sound O" },
    { class: "fa fa-file-text", name: "File Text" },
    { class: "fa fa-file-text-o", name: "File Text O" },
    { class: "fa fa-file-video-o", name: "File Video O" },
    { class: "fa fa-file-word-o", name: "File Word O" },
    { class: "fa fa-file-zip-o", name: "File Zip O" },
    { class: "fa fa-files-o", name: "Files O" },
    { class: "fa fa-film", name: "Film" },
    { class: "fa fa-filter", name: "Filter" },
    { class: "fa fa-fire", name: "Fire" },
    { class: "fa fa-fire-extinguisher", name: "Fire Extinguisher" },
    { class: "fa fa-firefox", name: "Firefox" },
    { class: "fa fa-flag", name: "Flag" },
    { class: "fa fa-flag-checkered", name: "Flag Checkered" },
    { class: "fa fa-flag-o", name: "Flag O" },
    { class: "fa fa-flash", name: "Flash" },
    { class: "fa fa-flask", name: "Flask" },
    { class: "fa fa-flickr", name: "Flickr" },
    { class: "fa fa-floppy-o", name: "Floppy O" },
    { class: "fa fa-folder", name: "Folder" },
    { class: "fa fa-folder-o", name: "Folder O" },
    { class: "fa fa-folder-open", name: "Folder Open" },
    { class: "fa fa-folder-open-o", name: "Folder Open O" },
    { class: "fa fa-font", name: "Font" },
    { class: "fa fa-fonticons", name: "Fonticons" },
    { class: "fa fa-fort-awesome", name: "Fort Awesome" },
    { class: "fa fa-forumbee", name: "Forumbee" },
    { class: "fa fa-forward", name: "Forward" },
    { class: "fa fa-foursquare", name: "Foursquare" },
    { class: "fa fa-frown-o", name: "Frown O" },
    { class: "fa fa-futbol-o", name: "Futbol O" },
    { class: "fa fa-gamepad", name: "Gamepad" },
    { class: "fa fa-gavel", name: "Gavel" },
    { class: "fa fa-gbp", name: "Gbp" },
    { class: "fa fa-ge", name: "Ge" },
    { class: "fa fa-gear", name: "Gear" },
    { class: "fa fa-gears", name: "Gears" },
    { class: "fa fa-genderless", name: "Genderless" },
    { class: "fa fa-get-pocket", name: "Get Pocket" },
    { class: "fa fa-gg", name: "Gg" },
    { class: "fa fa-gg-circle", name: "Gg Circle" },
    { class: "fa fa-gift", name: "Gift" },
    { class: "fa fa-git", name: "Git" },
    { class: "fa fa-git-square", name: "Git Square" },
    { class: "fa fa-github", name: "Github" },
    { class: "fa fa-github-alt", name: "Github Alt" },
    { class: "fa fa-github-square", name: "Github Square" },
    { class: "fa fa-gittip", name: "Gittip" },
    { class: "fa fa-glass", name: "Glass" },
    { class: "fa fa-globe", name: "Globe" },
    { class: "fa fa-google", name: "Google" },
    { class: "fa fa-google-plus", name: "Google Plus" },
    { class: "fa fa-google-plus-square", name: "Google Plus Square" },
    { class: "fa fa-google-wallet", name: "Google Wallet" },
    { class: "fa fa-graduation-cap", name: "Graduation Cap" },
    { class: "fa fa-gratipay", name: "Gratipay" },
    { class: "fa fa-group", name: "Group" },
    { class: "fa fa-h-square", name: "H Square" },
    { class: "fa fa-hacker-news", name: "Hacker News" },
    { class: "fa fa-hand-grab-o", name: "Hand Grab O" },
    { class: "fa fa-hand-lizard-o", name: "Hand Lizard O" },
    { class: "fa fa-hand-o-down", name: "Hand O Down" },
    { class: "fa fa-hand-o-left", name: "Hand O Left" },
    { class: "fa fa-hand-o-right", name: "Hand O Right" },
    { class: "fa fa-hand-o-up", name: "Hand O Up" },
    { class: "fa fa-hand-paper-o", name: "Hand Paper O" },
    { class: "fa fa-hand-peace-o", name: "Hand Peace O" },
    { class: "fa fa-hand-pointer-o", name: "Hand Pointer O" },
    { class: "fa fa-hand-rock-o", name: "Hand Rock O" },
    { class: "fa fa-hand-scissors-o", name: "Hand Scissors O" },
    { class: "fa fa-hand-spock-o", name: "Hand Spock O" },
    { class: "fa fa-hand-stop-o", name: "Hand Stop O" },
    { class: "fa fa-hashtag", name: "Hashtag" },
    { class: "fa fa-hdd-o", name: "Hdd O" },
    { class: "fa fa-header", name: "Header" },
    { class: "fa fa-headphones", name: "Headphones" },
    { class: "fa fa-heart", name: "Heart" },
    { class: "fa fa-heart-o", name: "Heart O" },
    { class: "fa fa-heartbeat", name: "Heartbeat" },
    { class: "fa fa-history", name: "History" },
    { class: "fa fa-home", name: "Home" },
    { class: "fa fa-hospital-o", name: "Hospital O" },
    { class: "fa fa-hotel", name: "Hotel" },
    { class: "fa fa-hourglass", name: "Hourglass" },
    { class: "fa fa-hourglass-1", name: "Hourglass 1" },
    { class: "fa fa-hourglass-2", name: "Hourglass 2" },
    { class: "fa fa-hourglass-3", name: "Hourglass 3" },
    { class: "fa fa-hourglass-end", name: "Hourglass End" },
    { class: "fa fa-hourglass-half", name: "Hourglass Half" },
    { class: "fa fa-hourglass-o", name: "Hourglass O" },
    { class: "fa fa-hourglass-start", name: "Hourglass Start" },
    { class: "fa fa-houzz", name: "Houzz" },
    { class: "fa fa-html5", name: "Html5" },
    { class: "fa fa-i-cursor", name: "I Cursor" },
    { class: "fa fa-ils", name: "Ils" },
    { class: "fa fa-image", name: "Image" },
    { class: "fa fa-inbox", name: "Inbox" },
    { class: "fa fa-indent", name: "Indent" },
    { class: "fa fa-industry", name: "Industry" },
    { class: "fa fa-info", name: "Info" },
    { class: "fa fa-info-circle", name: "Info Circle" },
    { class: "fa fa-inr", name: "Inr" },
    { class: "fa fa-instagram", name: "Instagram" },
    { class: "fa fa-institution", name: "Institution" },
    { class: "fa fa-internet-explorer", name: "Internet Explorer" },
    { class: "fa fa-intersex", name: "Intersex" },
    { class: "fa fa-ioxhost", name: "Ioxhost" },
    { class: "fa fa-italic", name: "Italic" },
    { class: "fa fa-joomla", name: "Joomla" },
    { class: "fa fa-jpy", name: "Jpy" },
    { class: "fa fa-jsfiddle", name: "Jsfiddle" },
    { class: "fa fa-key", name: "Key" },
    { class: "fa fa-keyboard-o", name: "Keyboard O" },
    { class: "fa fa-krw", name: "Krw" },
    { class: "fa fa-language", name: "Language" },
    { class: "fa fa-laptop", name: "Laptop" },
    { class: "fa fa-lastfm", name: "Lastfm" },
    { class: "fa fa-lastfm-square", name: "Lastfm Square" },
    { class: "fa fa-leaf", name: "Leaf" },
    { class: "fa fa-leanpub", name: "Leanpub" },
    { class: "fa fa-legal", name: "Legal" },
    { class: "fa fa-lemon-o", name: "Lemon O" },
    { class: "fa fa-level-down", name: "Level Down" },
    { class: "fa fa-level-up", name: "Level Up" },
    { class: "fa fa-life-bouy", name: "Life Bouy" },
    { class: "fa fa-life-buoy", name: "Life Buoy" },
    { class: "fa fa-life-ring", name: "Life Ring" },
    { class: "fa fa-life-saver", name: "Life Saver" },
    { class: "fa fa-lightbulb-o", name: "Lightbulb O" },
    { class: "fa fa-line-chart", name: "Line Chart" },
    { class: "fa fa-link", name: "Link" },
    { class: "fa fa-linkedin", name: "Linkedin" },
    { class: "fa fa-linkedin-square", name: "Linkedin Square" },
    { class: "fa fa-linux", name: "Linux" },
    { class: "fa fa-list", name: "List" },
    { class: "fa fa-list-alt", name: "List Alt" },
    { class: "fa fa-list-ol", name: "List Ol" },
    { class: "fa fa-list-ul", name: "List Ul" },
    { class: "fa fa-location-arrow", name: "Location Arrow" },
    { class: "fa fa-lock", name: "Lock" },
    { class: "fa fa-long-arrow-down", name: "Long Arrow Down" },
    { class: "fa fa-long-arrow-left", name: "Long Arrow Left" },
    { class: "fa fa-long-arrow-right", name: "Long Arrow Right" },
    { class: "fa fa-long-arrow-up", name: "Long Arrow Up" },
    { class: "fa fa-magic", name: "Magic" },
    { class: "fa fa-magnet", name: "Magnet" },
    { class: "fa fa-mail-forward", name: "Mail Forward" },
    { class: "fa fa-mail-reply", name: "Mail Reply" },
    { class: "fa fa-mail-reply-all", name: "Mail Reply All" },
    { class: "fa fa-male", name: "Male" },
    { class: "fa fa-map", name: "Map" },
    { class: "fa fa-map-marker", name: "Map Marker" },
    { class: "fa fa-map-o", name: "Map O" },
    { class: "fa fa-map-pin", name: "Map Pin" },
    { class: "fa fa-map-signs", name: "Map Signs" },
    { class: "fa fa-mars", name: "Mars" },
    { class: "fa fa-mars-double", name: "Mars Double" },
    { class: "fa fa-mars-stroke", name: "Mars Stroke" },
    { class: "fa fa-mars-stroke-h", name: "Mars Stroke H" },
    { class: "fa fa-mars-stroke-v", name: "Mars Stroke V" },
    { class: "fa fa-maxcdn", name: "Maxcdn" },
    { class: "fa fa-meanpath", name: "Meanpath" },
    { class: "fa fa-medium", name: "Medium" },
    { class: "fa fa-medkit", name: "Medkit" },
    { class: "fa fa-meh-o", name: "Meh O" },
    { class: "fa fa-mercury", name: "Mercury" },
    { class: "fa fa-microphone", name: "Microphone" },
    { class: "fa fa-microphone-slash", name: "Microphone Slash" },
    { class: "fa fa-minus", name: "Minus" },
    { class: "fa fa-minus-circle", name: "Minus Circle" },
    { class: "fa fa-minus-square", name: "Minus Square" },
    { class: "fa fa-minus-square-o", name: "Minus Square O" },
    { class: "fa fa-mixcloud", name: "Mixcloud" },
    { class: "fa fa-mobile", name: "Mobile" },
    { class: "fa fa-mobile-phone", name: "Mobile Phone" },
    { class: "fa fa-modx", name: "Modx" },
    { class: "fa fa-money", name: "Money" },
    { class: "fa fa-moon-o", name: "Moon O" },
    { class: "fa fa-mortar-board", name: "Mortar Board" },
    { class: "fa fa-motorcycle", name: "Motorcycle" },
    { class: "fa fa-mouse-pointer", name: "Mouse Pointer" },
    { class: "fa fa-music", name: "Music" },
    { class: "fa fa-navicon", name: "Navicon" },
    { class: "fa fa-neuter", name: "Neuter" },
    { class: "fa fa-newspaper-o", name: "Newspaper O" },
    { class: "fa fa-object-group", name: "Object Group" },
    { class: "fa fa-object-ungroup", name: "Object Ungroup" },
    { class: "fa fa-odnoklassniki", name: "Odnoklassniki" },
    { class: "fa fa-odnoklassniki-square", name: "Odnoklassniki Square" },
    { class: "fa fa-opencart", name: "Opencart" },
    { class: "fa fa-openid", name: "Openid" },
    { class: "fa fa-opera", name: "Opera" },
    { class: "fa fa-optin-monster", name: "Optin Monster" },
    { class: "fa fa-outdent", name: "Outdent" },
    { class: "fa fa-pagelines", name: "Pagelines" },
    { class: "fa fa-paint-brush", name: "Paint Brush" },
    { class: "fa fa-paper-plane", name: "Paper Plane" },
    { class: "fa fa-paper-plane-o", name: "Paper Plane O" },
    { class: "fa fa-paperclip", name: "Paperclip" },
    { class: "fa fa-paragraph", name: "Paragraph" },
    { class: "fa fa-paste", name: "Paste" },
    { class: "fa fa-pause", name: "Pause" },
    { class: "fa fa-pause-circle", name: "Pause Circle" },
    { class: "fa fa-pause-circle-o", name: "Pause Circle O" },
    { class: "fa fa-paw", name: "Paw" },
    { class: "fa fa-paypal", name: "Paypal" },
    { class: "fa fa-pencil", name: "Pencil" },
    { class: "fa fa-pencil-square", name: "Pencil Square" },
    { class: "fa fa-pencil-square-o", name: "Pencil Square O" },
    { class: "fa fa-percent", name: "Percent" },
    { class: "fa fa-phone", name: "Phone" },
    { class: "fa fa-phone-square", name: "Phone Square" },
    { class: "fa fa-photo", name: "Photo" },
    { class: "fa fa-picture-o", name: "Picture O" },
    { class: "fa fa-pie-chart", name: "Pie Chart" },
    { class: "fa fa-pied-piper", name: "Pied Piper" },
    { class: "fa fa-pied-piper-alt", name: "Pied Piper Alt" },
    { class: "fa fa-pinterest", name: "Pinterest" },
    { class: "fa fa-pinterest-p", name: "Pinterest P" },
    { class: "fa fa-pinterest-square", name: "Pinterest Square" },
    { class: "fa fa-plane", name: "Plane" },
    { class: "fa fa-play", name: "Play" },
    { class: "fa fa-play-circle", name: "Play Circle" },
    { class: "fa fa-play-circle-o", name: "Play Circle O" },
    { class: "fa fa-plug", name: "Plug" },
    { class: "fa fa-plus", name: "Plus" },
    { class: "fa fa-plus-circle", name: "Plus Circle" },
    { class: "fa fa-plus-square", name: "Plus Square" },
    { class: "fa fa-plus-square-o", name: "Plus Square O" },
    { class: "fa fa-power-off", name: "Power Off" },
    { class: "fa fa-print", name: "Print" },
    { class: "fa fa-product-hunt", name: "Product Hunt" },
    { class: "fa fa-puzzle-piece", name: "Puzzle Piece" },
    { class: "fa fa-qq", name: "Qq" },
    { class: "fa fa-qrcode", name: "Qrcode" },
    { class: "fa fa-question", name: "Question" },
    { class: "fa fa-question-circle", name: "Question Circle" },
    { class: "fa fa-quote-left", name: "Quote Left" },
    { class: "fa fa-quote-right", name: "Quote Right" },
    { class: "fa fa-ra", name: "Ra" },
    { class: "fa fa-random", name: "Random" },
    { class: "fa fa-rebel", name: "Rebel" },
    { class: "fa fa-recycle", name: "Recycle" },
    { class: "fa fa-reddit", name: "Reddit" },
    { class: "fa fa-reddit-alien", name: "Reddit Alien" },
    { class: "fa fa-reddit-square", name: "Reddit Square" },
    { class: "fa fa-refresh", name: "Refresh" },
    { class: "fa fa-registered", name: "Registered" },
    { class: "fa fa-remove", name: "Remove" },
    { class: "fa fa-renren", name: "Renren" },
    { class: "fa fa-reorder", name: "Reorder" },
    { class: "fa fa-repeat", name: "Repeat" },
    { class: "fa fa-reply", name: "Reply" },
    { class: "fa fa-reply-all", name: "Reply All" },
    { class: "fa fa-retweet", name: "Retweet" },
    { class: "fa fa-rmb", name: "Rmb" },
    { class: "fa fa-road", name: "Road" },
    { class: "fa fa-rocket", name: "Rocket" },
    { class: "fa fa-rotate-left", name: "Rotate Left" },
    { class: "fa fa-rotate-right", name: "Rotate Right" },
    { class: "fa fa-rouble", name: "Rouble" },
    { class: "fa fa-rss", name: "Rss" },
    { class: "fa fa-rss-square", name: "Rss Square" },
    { class: "fa fa-rub", name: "Rub" },
    { class: "fa fa-ruble", name: "Ruble" },
    { class: "fa fa-rupee", name: "Rupee" },
    { class: "fa fa-safari", name: "Safari" },
    { class: "fa fa-save", name: "Save" },
    { class: "fa fa-scissors", name: "Scissors" },
    { class: "fa fa-scribd", name: "Scribd" },
    { class: "fa fa-search", name: "Search" },
    { class: "fa fa-search-minus", name: "Search Minus" },
    { class: "fa fa-search-plus", name: "Search Plus" },
    { class: "fa fa-sellsy", name: "Sellsy" },
    { class: "fa fa-send", name: "Send" },
    { class: "fa fa-send-o", name: "Send O" },
    { class: "fa fa-server", name: "Server" },
    { class: "fa fa-share", name: "Share" },
    { class: "fa fa-share-alt", name: "Share Alt" },
    { class: "fa fa-share-alt-square", name: "Share Alt Square" },
    { class: "fa fa-share-square", name: "Share Square" },
    { class: "fa fa-share-square-o", name: "Share Square O" },
    { class: "fa fa-shekel", name: "Shekel" },
    { class: "fa fa-sheqel", name: "Sheqel" },
    { class: "fa fa-shield", name: "Shield" },
    { class: "fa fa-ship", name: "Ship" },
    { class: "fa fa-shirtsinbulk", name: "Shirtsinbulk" },
    { class: "fa fa-shopping-bag", name: "Shopping Bag" },
    { class: "fa fa-shopping-basket", name: "Shopping Basket" },
    { class: "fa fa-shopping-cart", name: "Shopping Cart" },
    { class: "fa fa-sign-in", name: "Sign In" },
    { class: "fa fa-sign-out", name: "Sign Out" },
    { class: "fa fa-signal", name: "Signal" },
    { class: "fa fa-simplybuilt", name: "Simplybuilt" },
    { class: "fa fa-sitemap", name: "Sitemap" },
    { class: "fa fa-skyatlas", name: "Skyatlas" },
    { class: "fa fa-skype", name: "Skype" },
    { class: "fa fa-slack", name: "Slack" },
    { class: "fa fa-sliders", name: "Sliders" },
    { class: "fa fa-slideshare", name: "Slideshare" },
    { class: "fa fa-smile-o", name: "Smile O" },
    { class: "fa fa-soccer-ball-o", name: "Soccer Ball O" },
    { class: "fa fa-sort", name: "Sort" },
    { class: "fa fa-sort-alpha-asc", name: "Sort Alpha Asc" },
    { class: "fa fa-sort-alpha-desc", name: "Sort Alpha Desc" },
    { class: "fa fa-sort-amount-asc", name: "Sort Amount Asc" },
    { class: "fa fa-sort-amount-desc", name: "Sort Amount Desc" },
    { class: "fa fa-sort-asc", name: "Sort Asc" },
    { class: "fa fa-sort-desc", name: "Sort Desc" },
    { class: "fa fa-sort-down", name: "Sort Down" },
    { class: "fa fa-sort-numeric-asc", name: "Sort Numeric Asc" },
    { class: "fa fa-sort-numeric-desc", name: "Sort Numeric Desc" },
    { class: "fa fa-sort-up", name: "Sort Up" },
    { class: "fa fa-soundcloud", name: "Soundcloud" },
    { class: "fa fa-space-shuttle", name: "Space Shuttle" },
    { class: "fa fa-spinner", name: "Spinner" },
    { class: "fa fa-spoon", name: "Spoon" },
    { class: "fa fa-spotify", name: "Spotify" },
    { class: "fa fa-square", name: "Square" },
    { class: "fa fa-square-o", name: "Square O" },
    { class: "fa fa-stack-exchange", name: "Stack Exchange" },
    { class: "fa fa-stack-overflow", name: "Stack Overflow" },
    { class: "fa fa-star", name: "Star" },
    { class: "fa fa-star-half", name: "Star Half" },
    { class: "fa fa-star-half-empty", name: "Star Half Empty" },
    { class: "fa fa-star-half-full", name: "Star Half Full" },
    { class: "fa fa-star-half-o", name: "Star Half O" },
    { class: "fa fa-star-o", name: "Star O" },
    { class: "fa fa-steam", name: "Steam" },
    { class: "fa fa-steam-square", name: "Steam Square" },
    { class: "fa fa-step-backward", name: "Step Backward" },
    { class: "fa fa-step-forward", name: "Step Forward" },
    { class: "fa fa-stethoscope", name: "Stethoscope" },
    { class: "fa fa-sticky-note", name: "Sticky Note" },
    { class: "fa fa-sticky-note-o", name: "Sticky Note O" },
    { class: "fa fa-stop", name: "Stop" },
    { class: "fa fa-stop-circle", name: "Stop Circle" },
    { class: "fa fa-stop-circle-o", name: "Stop Circle O" },
    { class: "fa fa-street-view", name: "Street View" },
    { class: "fa fa-strikethrough", name: "Strikethrough" },
    { class: "fa fa-stumbleupon", name: "Stumbleupon" },
    { class: "fa fa-stumbleupon-circle", name: "Stumbleupon Circle" },
    { class: "fa fa-subscript", name: "Subscript" },
    { class: "fa fa-subway", name: "Subway" },
    { class: "fa fa-suitcase", name: "Suitcase" },
    { class: "fa fa-sun-o", name: "Sun O" },
    { class: "fa fa-superscript", name: "Superscript" },
    { class: "fa fa-support", name: "Support" },
    { class: "fa fa-table", name: "Table" },
    { class: "fa fa-tablet", name: "Tablet" },
    { class: "fa fa-tachometer", name: "Tachometer" },
    { class: "fa fa-tag", name: "Tag" },
    { class: "fa fa-tags", name: "Tags" },
    { class: "fa fa-tasks", name: "Tasks" },
    { class: "fa fa-taxi", name: "Taxi" },
    { class: "fa fa-television", name: "Television" },
    { class: "fa fa-tencent-weibo", name: "Tencent Weibo" },
    { class: "fa fa-terminal", name: "Terminal" },
    { class: "fa fa-text-height", name: "Text Height" },
    { class: "fa fa-text-width", name: "Text Width" },
    { class: "fa fa-th", name: "Th" },
    { class: "fa fa-th-large", name: "Th Large" },
    { class: "fa fa-th-list", name: "Th List" },
    { class: "fa fa-thumb-tack", name: "Thumb Tack" },
    { class: "fa fa-thumbs-down", name: "Thumbs Down" },
    { class: "fa fa-thumbs-o-down", name: "Thumbs O Down" },
    { class: "fa fa-thumbs-o-up", name: "Thumbs O Up" },
    { class: "fa fa-thumbs-up", name: "Thumbs Up" },
    { class: "fa fa-ticket", name: "Ticket" },
    { class: "fa fa-times", name: "Times" },
    { class: "fa fa-times-circle", name: "Times Circle" },
    { class: "fa fa-times-circle-o", name: "Times Circle O" },
    { class: "fa fa-tint", name: "Tint" },
    { class: "fa fa-toggle-down", name: "Toggle Down" },
    { class: "fa fa-toggle-left", name: "Toggle Left" },
    { class: "fa fa-toggle-off", name: "Toggle Off" },
    { class: "fa fa-toggle-on", name: "Toggle On" },
    { class: "fa fa-toggle-right", name: "Toggle Right" },
    { class: "fa fa-toggle-up", name: "Toggle Up" },
    { class: "fa fa-trademark", name: "Trademark" },
    { class: "fa fa-train", name: "Train" },
    { class: "fa fa-transgender", name: "Transgender" },
    { class: "fa fa-transgender-alt", name: "Transgender Alt" },
    { class: "fa fa-trash", name: "Trash" },
    { class: "fa fa-trash-o", name: "Trash O" },
    { class: "fa fa-tree", name: "Tree" },
    { class: "fa fa-trello", name: "Trello" },
    { class: "fa fa-tripadvisor", name: "Tripadvisor" },
    { class: "fa fa-trophy", name: "Trophy" },
    { class: "fa fa-truck", name: "Truck" },
    { class: "fa fa-try", name: "Try" },
    { class: "fa fa-tty", name: "Tty" },
    { class: "fa fa-tumblr", name: "Tumblr" },
    { class: "fa fa-tumblr-square", name: "Tumblr Square" },
    { class: "fa fa-turkish-lira", name: "Turkish Lira" },
    { class: "fa fa-tv", name: "Tv" },
    { class: "fa fa-twitch", name: "Twitch" },
    { class: "fa fa-twitter", name: "Twitter" },
    { class: "fa fa-twitter-square", name: "Twitter Square" },
    { class: "fa fa-umbrella", name: "Umbrella" },
    { class: "fa fa-underline", name: "Underline" },
    { class: "fa fa-undo", name: "Undo" },
    { class: "fa fa-university", name: "University" },
    { class: "fa fa-unlink", name: "Unlink" },
    { class: "fa fa-unlock", name: "Unlock" },
    { class: "fa fa-unlock-alt", name: "Unlock Alt" },
    { class: "fa fa-unsorted", name: "Unsorted" },
    { class: "fa fa-upload", name: "Upload" },
    { class: "fa fa-usb", name: "Usb" },
    { class: "fa fa-usd", name: "Usd" },
    { class: "fa fa-user", name: "User" },
    { class: "fa fa-user-md", name: "User Md" },
    { class: "fa fa-user-plus", name: "User Plus" },
    { class: "fa fa-user-secret", name: "User Secret" },
    { class: "fa fa-user-times", name: "User Times" },
    { class: "fa fa-users", name: "Users" },
    { class: "fa fa-venus", name: "Venus" },
    { class: "fa fa-venus-double", name: "Venus Double" },
    { class: "fa fa-venus-mars", name: "Venus Mars" },
    { class: "fa fa-viacoin", name: "Viacoin" },
    { class: "fa fa-video-camera", name: "Video Camera" },
    { class: "fa fa-vimeo", name: "Vimeo" },
    { class: "fa fa-vimeo-square", name: "Vimeo Square" },
    { class: "fa fa-vine", name: "Vine" },
    { class: "fa fa-vk", name: "Vk" },
    { class: "fa fa-volume-down", name: "Volume Down" },
    { class: "fa fa-volume-off", name: "Volume Off" },
    { class: "fa fa-volume-up", name: "Volume Up" },
    { class: "fa fa-warning", name: "Warning" },
    { class: "fa fa-wechat", name: "Wechat" },
    { class: "fa fa-weibo", name: "Weibo" },
    { class: "fa fa-weixin", name: "Weixin" },
    { class: "fa fa-whatsapp", name: "Whatsapp" },
    { class: "fa fa-wheelchair", name: "Wheelchair" },
    { class: "fa fa-wifi", name: "Wifi" },
    { class: "fa fa-wikipedia-w", name: "Wikipedia W" },
    { class: "fa fa-windows", name: "Windows" },
    { class: "fa fa-won", name: "Won" },
    { class: "fa fa-wordpress", name: "Wordpress" },
    { class: "fa fa-wrench", name: "Wrench" },
    { class: "fa fa-xing", name: "Xing" },
    { class: "fa fa-xing-square", name: "Xing Square" },
    { class: "fa fa-y-combinator", name: "Y Combinator" },
    { class: "fa fa-y-combinator-square", name: "Y Combinator Square" },
    { class: "fa fa-yahoo", name: "Yahoo" },
    { class: "fa fa-yc", name: "Yc" },
    { class: "fa fa-yc-square", name: "Yc Square" },
    { class: "fa fa-yelp", name: "Yelp" },
    { class: "fa fa-yen", name: "Yen" },
    { class: "fa fa-youtube", name: "Youtube" },
    { class: "fa fa-youtube-play", name: "Youtube Play" },
    { class: "fa fa-youtube-square", name: "Youtube Square" }
]